CREATE TABLE groups (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(64) NOT NULL,
  is_public BOOLEAN DEFAULT(true) NOT NULL,
  pin VARCHAR(6) NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);