CREATE TABLE notes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(64) NOT NULL,
  slug VARCHAR(64) NOT NULL UNIQUE,
  body LONGTEXT NOT NULL, 
  archived BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);